✏️ Error message + invalid inputs

diff --git a/corona b/corona
--- a/corona
+++ b/corona
@@ -15,20 +15,27 @@ export LC_NUMERIC=en_US.UTF-8
 # reportovano_khs         9
 
 ############################## FUNCTIONS ##############################
-check_age() {
-    if [[ "$1" =~ ^[0-9]{1,3}$ ]] || [ "$1" == '' ]; then
-        return 0
-    else
-        EXIT_CODE="1"
-        return 1
-    fi
+awk_none_end () {
+    awk \
+    '{
+        if ($0 ~ /^None.*/)
+            none_line=$0
+        else if ($0 ~ /^>105.*/)
+            age_line=$0
+        else
+            print $0
+    } END {
+        if (age_line != "")
+            print age_line
+        if (none_line != "")
+            print none_line
+    }'
 }
 
 check_date() {
-    if [[ "$1" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] && [ -n "$(date -d "$1" 2>/dev/null)" ] || [ "$1" == '' ]; then
+    if [[ "$1" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] && [ -n "$(date -d "$1" 2>/dev/null)" ]; then
         return 0
     else
-        EXIT_CODE="1"
         return 1
     fi
 }
@@ -40,6 +47,16 @@ debug_print_values() {
     echo "-g $G_FILTER and $GENDER"
     echo "-s $S_FILTER and $WIDTH"
     echo "Command: $COMMAND"
+}
+
+error_msg() {
+    if [ "$1" == "" ]; then
+        echo "corona: $2" 1>&2
+    else
+        echo "corona: $1: $2" 1>&2
+    fi
+
+    exit "$3"
 }
 
 help() {
@@ -194,23 +211,6 @@ traverse_awk() {
         }'
 }
 
-awk_none_end () {
-    awk \
-    '{
-        if ($0 ~ /^None.*/)
-            none_line=$0
-        else if ($0 ~ /^>105.*/)
-            age_line=$0
-        else
-            print $0
-    } END {
-        if (age_line != "")
-            print age_line
-        if (none_line != "")
-            print none_line
-    }'
-}
-
 ############################## DATA ##############################
 # COMMANDS="infected merge gender age daily monthly yearly countries districts regions"
 COMMAND=""
@@ -223,30 +223,34 @@ WIDTH=""
 DISTRICT_FILE=""
 REGIONS_FILE=""
 
-EXIT_CODE="0"
 HEADER="id,datum,vek,pohlavi,kraj_nuts_kod,okres_lau_kod,nakaza_v_zahranici,nakaza_zeme_csu_kod,reportovano_khs"
 LOGS=""
+
+# exit codes
+EC_SUCCESS="0"
+EC_MUL_COMMANDS="1"
+EC_UNK_FILTER="2"
+EC_WRG_FARG="3"
 
 ############################## MAIN ##############################
 while [ "$#" -gt 0 ]; do
     case "$1" in
     infected | merge | gender | age | daily | monthly | yearly | countries | districts | regions)
-        if [ -z "$COMMAND" ]; then
-            COMMAND=$1
-        else
-            echo "Multiple commands not allowed" 1>&2
-            exit 1
-        fi
+        if [ -n "$COMMAND" ]; then error_msg "" "Multiple commands not allowed" "$EC_MUL_COMMANDS"; fi
+        COMMAND=$1
         ;;
     -a)
+        if ! check_date "$2"; then error_msg "$2" "Invalid date" "$EC_WRG_FARG"; fi
         A_DATETIME=$2
         shift
         ;;
     -b)
+        if ! check_date "$2"; then error_msg "$2" "Invalid date" "$EC_WRG_FARG"; fi
         B_DATETIME=$2
         shift
         ;;
     -g)
+        if [ "$2" != "M" ] && [ "$2" != "Z" ]; then error_msg "$2" "Unknown gender" "$EC_WRG_FARG"; fi
         GENDER=$2
         shift
         ;;
@@ -269,12 +273,8 @@ while [ "$#" -gt 0 ]; do
         exit 0
         ;;
     *)
-        if [[ $1 =~ ^-.*$ ]]; then
-            echo "Unknown filter" 1>&2
-            EXIT_CODE="1"
-        else
-            LOGS="$LOGS $1"
-        fi
+        if [[ $1 =~ ^-.*$ ]]; then error_msg "$1" "Unknown filter" "$EC_UNK_FILTER"; fi    
+        LOGS="$LOGS $1"
         ;;
     esac
     shift
@@ -309,4 +309,4 @@ else
     fi
 fi
 
-exit "$EXIT_CODE"
+exit "$EC_SUCCESS"
